first iteration
babkaizergil/java-filmorate pull request #2
Opened 2023-03-23 15:53 UTC by babkaizergil

add controllers and tests

2023-03-24 13:46 UTC, VertigoMaker requested changes
Хорошая рабта!

2023-03-24 13:46 UTC, VertigoMaker commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private void checkReleaseDate(Film film) {
Лучше завести один метод Validate где проводить валидацию фильма.

2023-03-24 13:46 UTC, VertigoMaker commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private long duration;
Обычно хватает int, т.к целочисленным считают обычно секунды(в редких случаях милисекунды), так что int хватит :).

2023-03-26 09:12 UTC, babkaizergil commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private long duration;
заменила

2023-03-26 10:34 UTC, babkaizergil commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private void checkReleaseDate(Film film) {
Завела.

2023-03-27 11:42 UTC, VertigoMaker approved these changes
Всё верно

2023-04-06 18:51 UTC, merged