first iteration (10)
babkaizergil/java-filmorate pull request #3
Opened 2023-04-13 11:28 UTC by babkaizergil

refactor, add validation, add methods

2023-04-13 13:08 UTC, VertigoMaker requested changes
Отличная работа

2023-04-14 07:21 UTC, babkaizergil commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +            Set<Integer> friends = user.getFriends();
Вынесла в отдельный метод работу с айдишниками

2023-04-14 13:22 UTC, VertigoMaker commented
Всё верно

2023-04-14 13:23 UTC, VertigoMaker approved these changes

2023-04-15 12:25 UTC, merged