Add database
babkaizergil/java-filmorate pull request #6
Opened 2023-05-04 12:21 UTC by babkaizergil

2023-05-04 22:08 UTC, EvgenyKoptubenko commented on README.md
> +    HAVING f.status = true;
точно ли этот запрос будет работать? Тут есть count по количеству друзей и группировка по user_id. Но что произойдет с name и login? Есть ли пример работы этого запроса?

2023-05-04 22:14 UTC, EvgenyKoptubenko commented
@RestControllerAdvice("ru.yandex.practicum.filmorate.controller")
public class ExceptionsHandler {

Возле метода 
@ExceptionHandler
    @ResponseStatus(HttpStatus.BAD_REQUEST) //500
    public Map<String, String> handleServerError(final ServiceException e) {
стоит комментарий 500, но Bad_Request это 400
BAD_REQUEST(400, HttpStatus.Series.CLIENT_ERROR, "Bad Request"),

Комментарий не понятен. Либо комментарии должны быть понятны без контекста, либо их нужно убирать.

2023-05-04 22:15 UTC, EvgenyKoptubenko commented
ExceptionHandler - обработчики BadRequest можно объединить в один. Попробуй https://spring.io/blog/2013/11/01/exception-handling-in-spring-mvc или https://www.baeldung.com/exception-handling-for-rest-with-spring

2023-05-04 22:17 UTC, EvgenyKoptubenko commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDbStorage.java
> +        Collections.sort(films, Comparator.comparingInt(Film::getId));
Когда достается один фильм, то отдельным селектом достаются жанры, а тут жанры к фильмам не приделываются

2023-05-04 22:17 UTC, EvgenyKoptubenko commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDbStorage.java
> +            SqlRowSet genreRows = jdbcTemplate.queryForRowSet(sqlQuery, id);
Попробуй сделать все в одном запросе, чтобы не вызывать базу данных много раз, когда можно вызвать один

2023-05-04 22:19 UTC, EvgenyKoptubenko commented
Пожалуйста, поправь все места, где сперва вытаскивается одна сущность из базы данных, а потом по ней делается еще один селект, чтобы вытащить дополнительные данные. Все должно выполняться в одном запросе

2023-05-04 22:20 UTC, EvgenyKoptubenko commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private List<Genre> genres = new ArrayList<>();
new ArrayList можно не писать

2023-05-04 22:22 UTC, EvgenyKoptubenko commented
По-моему для пользователя должны быть полный crud. Сейчас не работает удаление пользователя
curl --request DELETE \
  --url http://localhost:8080/users/2222 \
  --header 'Content-Type: multipart/form-data'

{
	"timestamp": "2023-05-04T22:20:51.612+00:00",
	"status": 405,
	"error": "Method Not Allowed",
	"path": "/users/2222"
}

2023-05-04 22:25 UTC, EvgenyKoptubenko commented
Если отправить запрос на создание пользователя два раза, то приходит ответ 404
curl --request POST \
  --url http://localhost:8080/users \
  --header 'Content-Type: application/json' \
  --header 'X-Sharer-User-Id: 12231' \
  --data '{
	"name":"nameItem1",
	"email":"email2@2email.com",
  "login":"login",
	"birthday":"2001-01-01"
}'

{
	"error": "Объект не найден.",
	"message": "Пользователь с похожими параметрами уже существует, id = 2"
}

Если пользователь с такими параметрами существует, то почему объект не найден?
Если это неверный запрос, то должен Bad Request, если запрос не проходит, потому что такой уже есть, то должен быть Conflict. Почему тут 404?

2023-05-04 22:25 UTC, EvgenyKoptubenko commented
Если отправить запрос такой, то падает
curl --request POST \
  --url http://localhost:8080/films \
  --header 'Content-Type: application/json' \
  --header 'X-Sharer-User-Id: 12231' \
  --data '{
	"name":"FilmName",
	"email":"email@email.com",
  "login":"login",
	"birthday":"2001-01-01",
	"duration":22
}'

java.lang.NullPointerException: null
	at ru.yandex.practicum.filmorate.service.FilmService.validate(FilmService.java:72) ~[classes/:na]
	at ru.yandex.practicum.filmorate.service.FilmService.create(FilmService.java:29) ~[classes/:na]
	at ru.yandex.practicum.filmorate.controller.FilmController.create(FilmController.java:35)

2023-05-04 22:29 UTC, EvgenyKoptubenko requested changes
Работа сделана нормально. Есть предложение по улучшению кода

2023-05-10 13:36 UTC, babkaizergil commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private List<Genre> genres = new ArrayList<>();
убрала и в User тоже

2023-05-10 13:48 UTC, babkaizergil commented on README.md
> +    HAVING f.status = true;
внесла правки

2023-05-13 01:53 UTC, EvgenyKoptubenko approved these changes
Работа сделана хорошо. Спасибо.

2023-05-13 07:38 UTC, merged